service:
  name: serverlessChallenge

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamondb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  create:
    handler: src/functions/createeEmployees.handle
    events:
      - http:
          path: /createEmployees
          method: /POST
          cors: true

  list:
    handler: src/functons/listEmployees.handle
    events:
      - http:
          path: /listEmployes:{id}
          method: /GET
          cors: true

  update:
    handler: src/functions/updateEmployees
    events:
      - http:
          path: /UpdateEmployees/{id}
          method: /PUT
          cors: true

  delete:
    handler: src/functions/deleteEmployees
    events:
      - http:
          path: employees/{id}
          method: /DELETE
          cors: true
resources:
  Resources:
    dbEmployee:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
